### ISSUE TITLE
Can not get hosts from http://sdk.open.api.igexin.com/serviceex

### ISSUE THREAD

**Issue by OceanMan8** [ShaoZeMing/laravel-getui#1]
请问有遇到过这个错么：
Can not get hosts from http://sdk.open.api.igexin.com/serviceex,http://sdk.open.api.gepush.com/serviceex,http://sdk.open.api.getui.net/serviceex,http://sdk1.open.api.igexin.com/serviceex,http://sdk2.open.api.igexin.com/serviceex,http://sdk3.open.api.igexin.com/serviceex|error:

**Comment by ShaoZeMing** [comment]
请问你是使用的是哪个版本?

**Comment by OceanMan8** [comment]
v1.1的

**Comment by ShaoZeMing** [comment]
我刚才测试了一下，一切正常，你能给出详细的操作以及报错吗？

**Comment by OceanMan8** [comment]
我就是按照你的配置做的啊，我现在有点怀疑是不是我的环境问题：
因为我是测试服务器，没有配置域名，是不是必须要配置域名呢

**Comment by ShaoZeMing** [comment]
你认证检查一下你的配置文件，很久没用了，我刚才composer安装了当前 版本，本地测试了一切正常。  请参考文档，  你可以在个推上查看对应的配置数据，如果不方便，你可以用包原配置文件 执行  这个方法测试一下，这里面的$deviceId 是我最新安装的测试包 cid 
```
    $deviceId = 'a1f3e7c11ca97924be6f291f2c09714b';
//        // 多个push对象device_id 用数组传入
//        $deviceId = [
//            'ea34a4715b08b1b8d77aabf36c977cba',
//            'ea34a4715b08b1b8d77aabf36c977cba',
//        ];

        $data = [
            'url' => 'http://test.4d4k.com/push',
            'type' => '点击查看\(^o^)/~',
            'title' => '23232323fdf',
            'content' => '今天天气真好',
            'id' => '3a92y3GR1neZ',
            'merchant_name' => '泽明科技',
            'big_cat' => '电视机',
            'full_address' => '北京市海淀区五道口清华大学',
        ];


        $res = \GeTui::push($deviceId, $data,true); //Using default default_client

        dd($res);
```

**Comment by OceanMan8** [comment]
我是把手机端的clientid存起来的，
我这边是每个商户一个定制的APP，所以每个商户都申请了一个个推应用，然后我把个推的APPKEY啥的都存到数据库的；
然后为了不改动源代码，我把查出来的配置 array_merge到config中的

$messages = NNOrderUserMessage::with('getuiConfig')
                ->where('type', '=', 3)
                ->whereDay('created_at', '=', Carbon::today())
                ->get();
            Log::info('推送消息个数：'.count($messages));
            // 把每个商户的APPID 放入到配置里
            $configs = NNMerchantGetuiConfig::all([
                'app_id AS gt_appid',
                'app_key AS gt_appkey',
                'app_secret AS gt_appsecret',
                'master_secret AS gt_mastersecret',
                'domain_url AS gt_domainurl',
                'message_logo',
                'bid'
            ])->keyBy('bid')->toArray();

            $getui_config = config('getui');
            $getui_config['production'] = $getui_config['production'] + $configs;
            Log::info('商户应用：', $getui_config['production']);
            // 推送消息
            $getui = new GeTuiService($getui_config);
            foreach ($messages as $message) {
                $client = NNMerchantGetuiClient::query()
                    ->where('bid', $message->bid)
                    ->where('user_id', $message->user_id)
                    ->first();
                if ($client) {
                    $data = [
                        'url' => $getui_config['production'][strval($message->bid)]['message_logo'],
                        'title' => '逾期提醒~~~',
                        'content' => '您有订单还有一天将逾期，请尽快处理！',
                    ];
                    $result = $getui->toClient(strval($message->bid))->push($client->client_id, $data);
                    Log::info('推送结果：'.json_encode($result, JSON_UNESCAPED_UNICODE));
                }
            }

**Comment by ShaoZeMing** [comment]
从逻辑上来讲，这个应该没有问题，你打印过你合并后的配置文件数据结构吗？ 或则你测试过简单发送能成功吗？

**Comment by OceanMan8** [comment]
请问下 data里面的url是什么参数

**Comment by ShaoZeMing** [comment]
那个 自己定义的，之前我们项目需要点击推送跳转，所以加的参数

**Comment by OceanMan8** [comment]
你能用我的参数 帮我试一下吗
AppID： 
8L7FE6HGxm92bzWAz8DKT2
AppSecret： 
qyhW3gBO947ou2Yi5Tb2i6
AppKey： 
KGKG5hZdmv6Ok1iFFgbt2
MasterSecret： 
UXNBBxnAhI8BUrfTxzWYs5

client_id : 26fb116333bc42691cc5abc02be90a55

**Comment by mitoop** [comment]
@OceanMan8 你这个问题 应该是client没选对 个推的代码是真烂
