### ISSUE TITLE
Lumen下无法集成本包。需要下载laravel/framework

### ISSUE THREAD

**Issue by Lysice** [ShaoZeMing/laravel-getui#3]
前提:这个包内依赖于Laravel/framework ~5.0 及以上。
1.我在lumen下下载情形 让我下laravel框架的依赖 这本身是有问题的。
2.项目lumen 集成了jwt 在安装laravel的时候 会安装laravel/auth 但是 我的jwt 就要求被卸载。
这是其中一个冲突。

**Comment by ShaoZeMing** [comment]
这个问题，我下午修复一下。

**Comment by ShaoZeMing** [comment]
@Lysice  已修复，请使用最新tag https://github.com/ShaoZeMing/laravel-getui/tree/v1.2.3
